#import './image.gql'
#import './video.gql'

# Helpers for making responsive assets

fragment responsiveImage on responsiveImage_BlockType {
	id
	landscape { ...image }
	portrait { ...image }
}

fragment responsiveSrcset on responsiveImage_BlockType {
	id
	landscape { ...srcset }
	portrait { ...srcset }
}

fragment responsiveVideo on responsiveVideo_BlockType {
	id
	landscape { ...video }
	portrait { ...video }
}
